
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    volumes:
      - mssql_data:var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    networks: 
      - hrm-network
    restart: unless-stopped
    healthcheck:
      test: >
        /opt/mssql-tools/bin/sqlcmd
        -S localhost
        -U sa
        -P "${DB_PASSWORD}"
        -Q "SELECT 1"
        || exit 1
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s


  backend:
    build: ./backend
    container_name: springboot_be
    environment:
      - DATASOURCE_USERNAME=sa
      - DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
      - DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - hrm-network
    

  frontend:
    build: ./frontend
    container_name: vue_fe
    ports:
      - ${FE_PORT:-80}:80
      # - 443:443
    volumes:
      - ~/webapp/uploads:/var/www/uploads:ro
      - ./frontend/${FRONTEND_NGINX_CONF:-nginx.conf}:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - hrm-network
    

volumes:
  mssql_data:


networks:
  hrm-network:
    driver: bridge